name: Scala CI

on: [push, pull_request]

jobs:
  sbt_tasks:
    strategy:
      matrix:
        jdk:
          - 8
          - 11
        command:
          - scalafmtCheckAll scalafmtSbtCheck
          - +test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - uses: coursier/cache-action@v3
      - name: Run `sbt ${{ matrix.command }}`
        run: ./sbt ${{ matrix.command }}
