on:
  schedule:
    - cron: '0 0 * * 0'
  repository_dispatch:
    types: [scala-steward]

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        # Switch to the official scala-steward-action when this PR is merged.
        # https://github.com/scala-steward-org/scala-steward-action/pull/176
        # uses: scala-steward-org/scala-steward-action@v2
        uses: xuwei-k/scala-steward-action@65461e9a57695ac4522cd0fb36ffa0596beab835
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
