on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - master
  repository_dispatch:
    types: [scala-steward]

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          # https://github.community/t/github-actions-bot-email-address/17204/6
          # https://api.github.com/users/github-actions%5Bbot%5D
          author-name: github-actions[bot]
          author-email: 41898282+github-actions[bot]@users.noreply.github.com
